from llama_cpp import Llama, LlamaGrammar


class Message:
    def __init__(self, agent: str, content: str) -> None:
        self.agent = agent
        self.content = content

    def __repr__(self) -> str:
        return f'<{self.agent}> {self.content}'


class Chat:

    SYSTEM_KEY = 'system'
    ASSISTANT_KEY = 'assistant'
    USER_KEY = 'user'

    CLEAR_CURRENT_LINE = '\33[2K\r'
    CHARSET = 'UTF-8'

    def __init__(
            self,
            model: Llama,
            n_generate: int,
            temperature: float = 0.8,
            top_p: float = 0.9,
            top_k: int = 40,
            agent_prefixes: dict[str, str] = {  # Default template (most common one)
                SYSTEM_KEY: '<|im_start|>system',
                ASSISTANT_KEY: '<|im_start|>assistant',
                USER_KEY: '<|im_start|>user'
            },
            agent_names: dict[str, str] = {  # Default agent names (most common ones)
                SYSTEM_KEY: 'system',
                ASSISTANT_KEY: 'assistant',
                USER_KEY: 'user'
            },
            bot: str = '',
            eos: str = '<|im_end|>',
            debug=False
    ) -> None:
        """
        Create a new Chat object

        @param model: the llama object that represents the model
        @param n_generate: the maximum number of tokens generated by the model in a single turn
        @param temperature: the temperature used for model inference
        @param top_p: the top_p used for model inference
        @param top_k: the top_k used for model inference
        @param agent_prefixes: the tokens used to wrap an agent name
        @param agent_names: the dict with the names for: system, assistant, user
        @param bot: the token that starts the chat
        @param eos: the token that ends a single chat round
        @param debug: whether or not to output debug informations
        """
        self.model = model
        self.bot = bot
        self.eos = eos
        self.n_generate = n_generate
        self.temperature = temperature
        self.top_p = top_p
        self.top_k = top_k
        self.agent_prefixes = agent_prefixes
        self.agent_names = agent_names
        self.debug = debug

        self.eos_token = self.tokenize_text(self.eos, add_bos=False, special=True)[0]
        self.bot_token = self.tokenize_text(self.bot, add_bos=False, special=True)[0] if len(self.bot) > 0 else None

        self.messages: list[Message] = []
        self.tokens_cache: list[int] = []
        self.cache_initialize()


    def generate_assistant_reply(self, grammar: LlamaGrammar | None = None) -> tuple[str, int]:
        """
        Get a response from the model (after a user message presumably) in a single final string.

        @param grammar: the grammar used to constrain the output of the model
        @return: the response text and the number of remaining tokens in the context
        """
        self.cache_append_header(agent=self.ASSISTANT_KEY)

        reply = ''
        n_reply_tokens = 0
        for token in self.model.generate(tokens=self.tokens_cache, temp=self.temperature, top_p=self.top_p, top_k=self.top_k, grammar=grammar):
            self.check_context_overflow()  # Check for context exceeded
            if token == self.model.token_eos() or token == self.eos_token:  # Check for EOS termination
                self.tokens_cache += self.tokenize_text(self.eos)
                break
            if n_reply_tokens >= self.n_generate:  # Check if the model generated more tokens than it should in this chat turn
                self.tokens_cache += self.tokenize_text(self.eos)
                break

            self.tokens_cache.append(token)
            n_reply_tokens += 1
            reply += self.detokenize_tokens([token])

            interrupt, reply = self.check_eos_failure(reply)                            # Check for EOS detection failure due to multiple EOS tokens
            if interrupt: break
            interrupt, reply = self.check_model_impersonation(reply, self.USER_KEY)     # Check for model trying to impersonate the user before EOS
            if interrupt: break
            interrupt, reply = self.check_model_impersonation(reply, self.SYSTEM_KEY)   # Check for model trying to impersonate the system before EOS
            if interrupt: break

        self.add_message(self.ASSISTANT_KEY, reply)

        return reply, self.context_available()


    def generate_assistant_reply_stepped(self, grammar: LlamaGrammar | None = None):
        """
        Get a response from the model (after a user message presumably) as a stream of tokens.

        @param grammar: the grammar used to constrain the output of the model
        @return: the single (already detokenized) token generated
        """
        self.cache_append_header(agent=self.ASSISTANT_KEY)

        reply = ''
        n_reply_tokens = 0
        for token in self.model.generate(tokens=self.tokens_cache, temp=self.temperature, top_p=self.top_p, top_k=self.top_k, grammar=grammar):
            self.check_context_overflow()
            if token == self.model.token_eos() or token == self.eos_token:  # Check for EOS termination
                self.tokens_cache += self.tokenize_text(self.eos)
                yield '\n'
                break
            if n_reply_tokens >= self.n_generate:  # Check for max tokens reached
                self.tokens_cache += self.tokenize_text(self.eos)
                yield '\n'
                break

            self.tokens_cache.append(token)
            n_reply_tokens += 1
            new_text = self.detokenize_tokens([token])
            reply += new_text

            interrupt, reply = self.check_eos_failure(reply)
            if interrupt:  # Remove the broken EOS text from the terminal
                n_char_to_delete = len(self.eos) - 1
                back_str = '\b' * n_char_to_delete
                empty_str = ' ' * n_char_to_delete
                yield back_str + empty_str + '\n'
                break
            interrupt, reply = self.check_model_impersonation(reply, self.USER_KEY)
            if interrupt:  # Remove the text generated by the impersionation from the terminal
                yield self.CLEAR_CURRENT_LINE
                break
            interrupt, reply = self.check_model_impersonation(reply, self.SYSTEM_KEY)
            if interrupt:  # Remove the text generated by the impersionation from the terminal
                yield self.CLEAR_CURRENT_LINE
                break

            yield new_text

        self.add_message(self.ASSISTANT_KEY, reply)


    def send_message(self, agent: str, content: str) -> int:
        """
        Append a message to the context of the chat

        @param agent: the agent that sent the content
        @param content: the content of the message
        @return: the available context after appending the message
        """
        new_message = self.add_message(agent, content)
        self.cache_append_message(new_message)

        return self.context_available()


    def add_message(self, agent: str, content: str) -> Message:
        """
        Create a new message and append it to the messages saved.
        It does NOT add the message or its content to the contex.

        @param agent: the agent that sent the content
        @param content: the content of the message
        @return: the message created from the agent and content
        """
        new_message = Message(agent=agent, content=content)
        self.messages.append(new_message)

        return new_message


    def check_eos_failure(self, reply: str) -> tuple[bool, str]:
        """
        Check if the model outputted an EOS token that was not properly tokenized.
        For example 3 tokens like `'<|' + 'end' + '|>'` instead of the single EOS
        token `'<|eos|>'`.

        @param reply: the reply of the assistant
        @return: a tuple `(is_escape_detected, cleaned_reply)`
        """
        interrupt = False
        if self.eos in reply[-(len(self.eos)+1):]:
            if self.debug: print(f'[DEBUG] EOS escape occurred: {reply[-len(self.eos):]}')
            reply = reply[:-len(self.eos)]
            # TODO: Should re-add single-token EOS here?
            interrupt = True

        return interrupt, reply


    def check_model_impersonation(self, reply: str, agent: str) -> tuple[bool, str]:
        """
        Check if the model tried to impersonate the user (usually by completely skipping the EOS).

        @param reply: the reply of the assistant
        @param agent: the agent that the model may have impersonated (usually the user or itself)
        @return: a tuple `(is_impersonation_detected, cleaned_reply)`
        """
        interrupt = False
        if self.agent_prefixes[agent] in reply:
            if self.debug: print(f'[DEBUG] Impersonation of {agent} detected')
            reply = reply.split(self.agent_prefixes[agent])[0].strip()
            interrupt = True

        return interrupt, reply


    def cache_initialize(self) -> None:
        """
        Initialize the context and re-add the BOS if needed
        """
        self.tokens_cache = []
        if self.bot_token:  # Add the BOT if specified
            self.tokens_cache.append(self.bot_token)


    def cache_append_header(self, agent: str) -> None:
        """
        Add the starting header for an agent to the context

        @param agent: the agent for which the header will be added
        """
        header = f'{self.agent_prefixes[agent]}'
        self.tokens_cache += self.tokenize_text(header)


    def cache_append_message(self, message: Message) -> None:
        """
        Append a message to the context tokens

        @param message: the message that will be added
        """
        round_text = f'{self.agent_prefixes[message.agent]}{message.content}{self.eos}'
        self.tokens_cache += self.tokenize_text(round_text)


    def cache_rebuild(self) -> None:
        """
        Rebuild the cache by using the messages list contained in the
        Chat object
        """
        self.cache_initialize()

        for msg in self.messages:
            self.cache_append_message(msg)


    def reset_chat(self, keep_system: bool = False) -> None:
        """
        Reset the chat, including context and messages

        @param keep_system: if the system messages should be kept in context or not
        """
        self.cache_initialize()

        if keep_system:
            # Remove all the non-system messages
            self.messages = [msg for msg in self.messages if msg.agent == self.SYSTEM_KEY]

            # Re-add the system messages to the token cache
            for msg in self.messages:
                self.cache_append_message(msg)
        else:
            self.messages = []


    def detokenize_tokens(self, tokens: list[int], special: bool = True) -> str:
        """
        Detokenize the tokens list to a string

        @param tokens: the list of tokens
        """
        errors_strategy = 'ignore'
        try:
            return self.model.detokenize(tokens, special=special).decode(self.CHARSET, errors=errors_strategy)
        except:
            print('[ERROR] An error occurred during detokenization of:', tokens)
            exit(1)


    def tokenize_text(self, text: str, add_bos: bool = False, special: bool = True) -> list[int]:
        """
        Tokenize the string list to a list of tokens

        @param text: the text totokenize
        @param add_bos: whether or not the BOS token needs to be added
        @param special: whether or not special tokens should be encoded as such
        @return: the list of tokens
        """
        try:
            return self.model.tokenize(text=bytes(text, self.CHARSET), add_bos=add_bos, special=special)
        except:
            print('[ERROR] An error occurred during tokenization of:', text)
            exit(1)


    def check_context_overflow(self):
        """
        Check if the context available was finished
        """
        if self.context_available() <= 0:
            print('[ERROR] Context exceeded.')
            exit(1)


    def print_stats(self):
        """
        Print some stats about the chat
        """
        print(f'Tokens used: {self.tokens_used()}')
        print(f'Tokens left: {self.context_available()}')


    def context_available(self) -> int:
        """
        Get the available context in the chat

        @return: the available number of tokens in the context
        """
        return self.model.n_ctx() - self.tokens_used()


    def tokens_used(self) -> int:
        """
        Get the tokens used until now in the context

        @return: the number of used tokens in the context
        """
        return len(self.tokens_cache)


    def get_raw_chat(self) -> str:
        """
        Get the raw chat text

        @return: the raw chat
        """
        return self.detokenize_tokens(self.tokens_cache)
