from llama_cpp import Llama, LlamaGrammar


class Message:
    def __init__(self, agent: str, content: str) -> None:
        self.agent = agent
        self.content = content


class Chat:

    CLEAR_CURRENT_LINE = '\33[2K\r'
    CHARSET = 'UTF-8'

    def __init__(
            self,
            model: Llama,
            bot: str,
            eos: str,
            n_generate: int,
            agent_prefixes: dict[str, str] = {
                'system': '<|im_start|>system',
                'assistant': '<|im_start|>assistant',
                'user': '<|im_start|>user'
            },
            agent_names: dict[str, str] = {
                'system': 'system',
                'assistant': 'assistant',
                'user': 'user'
            },
            debug=False
    ) -> None:
        """
        Create a new Chat object

        @param model: the llama object that represents the model
        @param bot: the token that starts the chat
        @param eos: the token that ends a single chat round
        @param n_generate: the maximum number of tokens generated by the model in a single turn
        @param agent_prefixes: the tokens used to wrap an agent name
        @param agent_names: the dict with the names for: system, assistant, user
        @param debug: whether or not to output debug informations
        """
        self.model = model
        self.bot = bot
        self.eos = eos
        self.n_generate = n_generate
        self.agent_prefixes = agent_prefixes
        self.agent_names = agent_names
        self.debug = debug

        self.messages: list[Message] = []
        self.tokens_cache: list[int] = []

        self.tokens_cache += self.tokenize_text(self.bot)


    def generate_reply(self, grammar: LlamaGrammar | None = None) -> tuple[str, int]:
        pass


    def generate_reply_stepped(self, grammar: LlamaGrammar | None = None):
        pass


    def add_message(self, agent: str, content: str) -> int:
        new_message = Message(agent=agent, content=content)
        self.messages.append(new_message)
        self.update_cache_last_msg()

        return self.context_available()


    def check_eos_failure(self, full_reply: str) -> tuple[bool, str]:
        interrupt = False
        if self.eos in full_reply[-(len(self.eos)+1):]:
            if self.debug: print(f'[DEBUG] EOS escape occurred: {full_reply[-len(self.eos):]}')
            full_reply = full_reply[:-len(self.eos)]
            interrupt = True

        return interrupt, full_reply


    def check_model_impersonation(self, full_reply: str, agent: str) -> tuple[bool, str]:
        interrupt = False
        if self.agent_prefixes[agent] in full_reply:
            if self.debug: print(f'[DEBUG] Impersonation of {agent} detected')
            full_reply = full_reply.split(self.agent_prefixes[agent])[0].strip()
            interrupt = True

        return interrupt, full_reply


    def update_cache_last_msg(self) -> None:
        last_message = self.messages[-1]
        agent = last_message.agent
        round_text = f'{self.agent_prefixes[agent]}{last_message.content}{self.eos}'

        self.tokens_cache += self.tokenize_text(round_text)


    def reload_cache(self) -> None:
        pass


    def detokenize_text(self, tokens: list[int]) -> str:
        errors_strategy = 'ignore'
        try:
            return self.model.detokenize(tokens).decode(self.CHARSET, errors=errors_strategy)
        except:
            print('[ERROR] An error occurred during detokenization of:', tokens)
            exit(1)


    def tokenize_text(self, text: str) -> list[int]:
        try:
            return self.model.tokenize(bytes(text, self.CHARSET), add_bos=False)
        except:
            print('[ERROR] An error occurred during tokenization of:', text)
            exit(1)


    def check_context_overflow(self):
        if self.context_available() <= 0:
            print('[ERROR] Context exceeded.')
            exit(1)


    def print_stats(self):
        print(f'Tokens used: {self.tokens_used()}')
        print(f'Tokens left: {self.context_available()}')


    def context_available(self) -> int:
        return self.model.n_ctx() - self.tokens_used()


    def tokens_used(self) -> int:
        return len(self.tokens_cache)
